const app = require('express')()
const axios = require ('axios')
const bodyParser = require('body-parser')

app.use(bodyParser.json())

app.listen(8080)

// API1 calls API2
// API2 sends a randomly generated value back to API1
// API1 sends this value to API3
// API3 returns this value along with another randomly generated value and their sum back to API1

app.post('/API3', (req,res) => {

    a = req.body.a
    let b = Math.floor(Math.random() * 10)
    console.log('Random Number Generated by API3: ' + b)

    res.json({

        a: a,
        b: b,
        sum: a + b
    })
})

app.get('/API2', (req,res) => {

    let a = Math.floor(Math.random() * 10)
    console.log('Random Number Generated by API2: ' + a)

    res.json({

        a: a
    })
})

app.get('/API1', async (req,res) => {

    try
    
    {
        const apiResponse1 = await axios({

        method: 'GET',
        url: 'http://127.0.0.1:8080/API2'

        })
    
        const apiResponse2 = await axios({

            method: 'POST',
            url: 'http://127.0.0.1:8080/API3',

            data:

            {
                a: apiResponse1.data.a
            }
        })

        res.send('Value Generated by API1: ' + apiResponse2.data.a + '\nValue Generated by API2: ' + apiResponse2.data.b + '\nSum: ' + apiResponse2.data.sum)
    } 
    
    catch(e) 
    
    {
        res.send('Error Occurred While Calling API')
    }
})