const app = require('express')()
const axios = require ('axios')
const bodyParser = require('body-parser')

app.use(bodyParser.json())
app.listen(8080)

// API1 generates a random number and sends it to API2
// API2 passed along this received number along with another randomly generated number to API3
// API3 adds both of these numbers and returns result to console
// It is mandatory for an API to return something as there would not be any way of knowing if it's done executing otherwise
// even if all it returns is a status code along with a message
// we end up getting a request timed out message if an API does not return anything

app.post('/API3', (req,res) => {

    sum = req.body.a + req.body.b
    console.log('\nSum of Randomly Generated Numbers ' + req.body.a + ' and ' + req.body.b + ': ' + sum + '\nAhan')

    res.status(200).send("OK")

})

app.post('/API2', async (req,res) => {
    
    let a = req.body.a    
    let b = Math.floor(Math.random() * 10)

    console.log('Number Generated by API2: ' + b)
    
    const apiResponse = await axios({
        
        method: 'POST',
        url: 'http://127.0.0.1:8080/API3',
        
        data:
        
        {
            a: a,
            b: b
        }
    })

    res.status(200).send("OK")
})

app.get('/API1', async (req,res) => {

    let a = Math.floor(Math.random() * 10)
    console.log('Number Generated by API1: ' + a)

    const apiResponse = await axios({
        
        method: 'POST',
        url: 'http://127.0.0.1:8080/API2',

        data:

        {
            a: a
        }
    })

    res.status(200).send("OK")
})