const app = require("express")();
const axios = require("axios");
const bodyParser = require("body-parser");

app.use(bodyParser.json());

app.listen(8080);

// API1 calls API2
// API2 generates a random number and sends it to API3
// API3 generates another random number and adds it to the input received from API2
// API3 sends this sum along with the numbers to API2
// API2 sends all three values back to API1

app.post("/API3", (req, res) => {
  // API3 calculates sum of a randomly generated number along with received number from API2

  // generates a random number and sends back the received value as is

  let a = req.body.a;
  let b = Math.floor(Math.random() * 10);

  let sum = a + b;

  console.log("Number Generated by API3: " + b);

  // res.json() is used to return a json response

  res.json({
    a: a,
    b: b,
    sum: sum,
  });
});

app.get("/API2", async (req, res) => {
  // API2 generates a random number and sends the result to API3

  let a = Math.floor(Math.random() * 10);
  console.log("Number Generated by API2: " + a);

  const apiResponse = await axios({
    method: "POST",
    url: "http://127.0.0.1:8080/API3",

    data: {
      a: a,
    },
  });

  res.json({
    a: apiResponse.data.a,
    b: apiResponse.data.b,
    sum: apiResponse.data.sum,
  });
});

app.get("/API1", async (req, res) => {
  // API1 calls API2

  const apiResponse = await axios({
    method: "GET",
    url: "http://127.0.0.1:8080/API2",
  });

  res.send(
    "Random Number (API2): " +
      apiResponse.data.a +
      "\nRandom Number (API3) " +
      apiResponse.data.b +
      "\nSum: " +
      apiResponse.data.sum +
      "\nAhan"
  );
});
