const app = require("express")();
const axios = require("axios");

app.listen(8080);

app.get("/API", (req, res) => {
  // generates and returns a random number

  let num = Math.floor(Math.random() * 10);
  console.log("Number Generated by API: " + num);

  // res.json() is used to return a json response

  res.json(num);
});

app.get("/APITest", async (req, res) => {
  const apiResponse = await axios({
    method: "GET",
    url: "http://127.0.0.1:8080/API",
  });

  res.send("Random Number: " + apiResponse.data); // if only single value use apiResponse.data
});
