services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
      # - .:/TestAPI
    ports:
      - 8000:8000
    # image: testapi:local
    image: testapi:remote
    # container_name: TestAPILocal
    container_name: TestAPIRemote